-- Create database
CREATE DATABASE TeknorixJobsDB;
GO

USE TeknorixJobsDB;
GO

-- ======================
--  Departments Table
-- ======================
CREATE TABLE Departments (
    DepartmentId INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL
);

-- Sample Departments
INSERT INTO Departments (Title) VALUES
('Software Development'),
('Project Management'),
('Human Resources'),
('Sales');

-- ======================
--  Locations Table
-- ======================
CREATE TABLE Locations (
    LocationId INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL,
    City NVARCHAR(100),
    State NVARCHAR(100),
    Country NVARCHAR(100),
    Zip INT
);

-- Sample Locations
INSERT INTO Locations (Title, City, State, Country, Zip) VALUES
('US Head Office', 'Baltimore', 'MD', 'United States', 21202),
('India Office', 'Goa', 'GA', 'India', 403001);

-- ======================
--  Jobs Table
-- ======================
CREATE TABLE Jobs (
    JobId INT IDENTITY(1,1) PRIMARY KEY,
    Code NVARCHAR(50) UNIQUE, -- Autogenerated code like JOB-01
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX),
    LocationId INT NOT NULL,
    DepartmentId INT NOT NULL,
    PostedDate DATETIME DEFAULT GETDATE(),
    ClosingDate DATETIME NULL,

    CONSTRAINT FK_Jobs_Department FOREIGN KEY (DepartmentId) REFERENCES Departments(DepartmentId),
    CONSTRAINT FK_Jobs_Location FOREIGN KEY (LocationId) REFERENCES Locations(LocationId)
);

-- Trigger or procedure could be added to auto-generate Job Codes
-- For simplicity, insert manually for now
INSERT INTO Jobs (Code, Title, Description, LocationId, DepartmentId, ClosingDate)
VALUES ('JOB-01', 'Software Developer', 'Develop and maintain web apps', 2, 1, '2025-12-31');

INSERT INTO Jobs (Code, Title, Description, LocationId, DepartmentId, ClosingDate)
VALUES ('JOB-02', 'Project Manager', 'Manage project delivery and clients', 1, 2, '2025-11-30');
